version: 2
jobs:
  build:
    docker:
      # TODO: Replace with a hugo dedicated build image
      - image: alpine:latest
    working_directory: /wojtek.bednarzak.com
    environment:
      - HUGO_VERSION: "0.37.1"
    steps:
      - run:
          name: "Install OS dependencies"
          command: apk add -U wget git openssh-client
      - checkout
      - run:
          name: "Download Hugo"
          command: /wojtek.bednarzak.com/.circleci/install.sh
      - run:
          name: "Build Site"
          command: HUGO_ENV=production hugo -v
      - run:
          name: "Deploy if on master"
          command: if [ $CIRCLE_BRANCH = 'master' ]; then /wojtek.bednarzak.com/.circleci/deploy.sh; fi
